name: Continuous Integration

on: 
  push:
    tags-ignore:
      - '*.*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.16.0
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.0
        run: npm install && npm run format && npm run lint 
