name: Continuous Delivery
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Cache Distribution Files
        uses: actions/cache@v1
        id: cache-dist
        with:
          path: ~/dist
          key: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        if: steps.cache-distributions-files.outputs.cache-hit != 'true'
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
