name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Cache Dependencies
        uses: actions/cache@v1
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

  format:
    name: Format
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Cache Dependencies
        uses: actions/cache@v1
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}

      - name: Format
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          run: npm run format:check -- --base=github.base_ref --head=github.head_ref

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Cache Dependencies
        uses: actions/cache@v1
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}

      - name: Lint
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          run: npm run affected:lint -- --base=github.base_ref --head=github.head_ref --parallel
