name: Continuous Deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Cache Dependencies
        uses: actions/cache@v1
        id: cache-dependencies
        with:
          path: ~/node_modules
          key: ${{ hashFiles('~/package.json') }}
      - name: Cache Distributions Files
        uses: actions/cache@v1
        id: cache-dependencies
        with:
          path: ~/dist
          key: dist
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run build ui-portfolio -- --configuration=production && npm run build ui-admin -- --configuration=production
